---
- name: "Generate cilium yaml"
  template:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - {src: "cilium.yaml.j2", dest: "/tmp/cilium.yaml"}
  tags: cilium

- name: "Deploy cilium"
  shell: "kubectl apply -f /tmp/cilium.yaml"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  tags: cilium
