---
- name: "Install keepalived"
  package:
    name: keepalived
    state: present

- name: "Generate keepalived.conf"
  template:
    src: "keepalived.conf.j2"
    dest: "/etc/keepalived/keepalived.conf"
  notify:
    - restart keepalived

- name: "Generate check_haproxy.sh"
  template:
    src: "check_haproxy.sh.j2"
    dest: "/etc/keepalived/check_haproxy.sh"
    mode: 0777
  notify:
    - restart keepalived
